# src/main/resources/application.yml для user-service

spring:
  application:
    name: be-logistics-platform-user-service

  # DataSource для PostgreSQL (основная БД)
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jackson:
    serialization: # чтобы Jackson правильно сериализует/десериализует.
      write-dates-as-timestamps: false
    time-zone: UTC

  # JPA / Hibernate
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
        default_schema: user_schema
    open-in-view: false

  liquibase:
    enabled: true
#    enabled: false   # временно отключаем Liquibase
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: user_schema
#    rollback-file: classpath:db/changelog/rollback.sql  # файл для SQL отката

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/logistics
          jwk-set-uri: http://localhost:8080/realms/logistics/protocol/openid-connect/certs

logging:
  level:
    com.innowise.logistics.platform.user: DEBUG
    liquibase: INFO

#  # MongoDB (для событий/логов)
#  data:
#    mongodb:
#      uri: mongodb://root:root@localhost:27017/logistics_events?authSource=admin
#
#  # Security (Keycloak)
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8080/realms/logistics
#          jwk-set-uri: http://localhost:8080/realms/logistics/protocol/openid-connect/certs
#
## Сервер
#server:
#  port: 8081
#  servlet:
#    context-path: /api/v1
#
## Логирование
#logging:
#  level:
#    com.innowise.logistics.userservice: DEBUG
#    org.springframework.web: INFO
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [%t] %-40.40logger{39} : %m%n"
#
## Management / Actuator
#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info,metrics,prometheus
#  endpoint:
#    health:
#      show-details: always
#  metrics:
#    export:
#      prometheus:
#        enabled: true
#
## Swagger / OpenAPI
#springdoc:
#  api-docs:
#    path: /api-docs
#  swagger-ui:
#    path: /swagger-ui.html
#    operationsSorter: method